---
name: Raytracing

on:
  push:
    branches:
      - main
    tags:
      - "*"
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up cache
        uses: actions/cache@v4
        with:
          path: build/_deps
          key: ${{ runner.os }}-deps-${{ hashFiles('CMakeLists.txt') }}

      - name: Set up C++
        run: |
          sudo apt-get update && sudo apt-get install -y \
            cmake \
            libc6-dev
        shell: bash

      - name: Build
        run: |
          mkdir -p build
          cd build
          cmake ..
          cmake --build .
        shell: bash

      - name: Test
        run: |
          cd build
          ctest --test-dir tests --output-on-failure
        shell: bash

      - if: startsWith(github.ref, 'refs/tags/')
        name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: build/bin/RaytracingExecutable
          generate_release_notes: true
          make_latest: true
